name: jedha-doordash1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build the Docker image
        run: docker build -t doordash/delivery-fee-service .

      - name: Launch the Docker container
        run: docker run -d -p 8080:8090 doordash/delivery-fee-service

      - name: Wait for the app to be ready
        run: sleep 3

      - name: Install python dependencies
        run: pip install pytest requests

      - name: Run tests
        run: pytest -v tests/